### ISSUE TITLE
great app but....

### ISSUE THREAD

**Issue by loso921** [KMindeguia/moviedbapp#3]
this is good but an error keeps popping out but can't seem TO FIND SOLUTION. the error is : linker command failed with exit code 1 (use -v to see invocation). Do you know the solution ?

**Comment by fbara** [comment]
I was able to download the source and it runs fine for me.  My guess is you're missing one of the standard libraries that he's using.

**Comment by KMindeguia** [comment]
@loso921 Sorry for the late reply mate.
Make sure you use the .xcworkspace and not the .xcodeproj project file :)
