### ISSUE TITLE
iOS 9 http issue

### ISSUE THREAD

**Issue by swapnilagarwwal** [KMindeguia/moviedbapp#6]
in iOS 9, the code gives warning and doesn't call API.
It can be easily fixed.
http://stackoverflow.com/questions/30731785/how-do-i-load-an-http-url-with-app-transport-security-enabled-in-ios-9

**Comment by KMindeguia** [comment]
@agarwalswapnil  Fixed in : 2fbfefe7ebbe088a3c588da7b9e71221d15b5d09

Thanks for raising the issue! :)
