### ISSUE TITLE
question: video player

### ISSUE THREAD

**Issue by ninokierulf** [KMindeguia/moviedbapp#7]
hi, i just wanted to ask what control do you use for video playback?
like for a local, or live stream.
if you arent using any control, is your implementation using avplayer or mpmovie?
i have researched so much for a simple yet powerful with clean architecture and i cant find.
would you be willing to collaborate in developing such control, and in the process also learn from each other?

ps: are you a member of any slack, so we could chat there.

thanks.

**Comment by KMindeguia** [comment]
@ninokierulf Hi! I'm afraid there's no video playback control in this project. But I do have a video player which uses the avplayer api that I've developed for an app of mine (you can check it out here : http://appsto.re/gb/Mn3J5.i) although I'm not sure I want to open source it. It all depends on what you may want to use it for.

ps: just send me your email address and I'll send you a slack invite.

**Comment by ninokierulf** [comment]
@KMindeguia my email add is ninokierulf@gmail.com

**Comment by KMindeguia** [comment]
@ninokierulf Invited :)
